### ISSUE TITLE
Make issues out of our Wunschliste

### ISSUE THREAD

**Issue by HallowXIII** [HallowXIII/PyLaut#2]
Issue trackers are a nice thing b/c you can tick the box when you have implemented e.g. unlimited rice pudding and they provide an incidental way of logging conversation.

**Comment by pthagnar** [comment]
lamentably, unlimited rice pudding is unimplementable

**Comment by pthagnar** [comment]
One of the ProTips i saw when doing this was about ignoring ur own issues #relatable
